# Generated by Django 5.1.6 on 2025-03-07 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.CharField(choices=[('house', 'House Loan'), ('car', 'Car Loan')], default='house', max_length=20),
        ),
        migrations.AddField(
            model_name='loanpolicy',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanpolicy',
            name='category',
            field=models.CharField(choices=[('house', 'House Loan'), ('car', 'Car Loan')], default='house', max_length=20),
        ),
        migrations.AddField(
            model_name='loanpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
