# Generated by Django 5.1.6 on 2025-03-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_category_loanpolicy_active_loanpolicy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpolicy',
            name='bank_personnel',
            field=models.ForeignKey(limit_choices_to={'role': 'bank'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_policies', to=settings.AUTH_USER_MODEL),
        ),
    ]
